/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface CheersInterface extends utils.Interface {
  functions: {
    "daosData()": FunctionFragment;
    "getMyPoolAddress(address)": FunctionFragment;
    "newDaoPoolFactory(string,string,string)": FunctionFragment;
    "newUserPoolFactory(string,string,string)": FunctionFragment;
    "usersData()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "daosData"
      | "getMyPoolAddress"
      | "newDaoPoolFactory"
      | "newUserPoolFactory"
      | "usersData"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "daosData", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getMyPoolAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "newDaoPoolFactory",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "newUserPoolFactory",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(functionFragment: "usersData", values?: undefined): string;

  decodeFunctionResult(functionFragment: "daosData", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMyPoolAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "newDaoPoolFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "newUserPoolFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usersData", data: BytesLike): Result;

  events: {};
}

export interface Cheers extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CheersInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    daosData(overrides?: CallOverrides): Promise<[string]>;

    getMyPoolAddress(
      _ownerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    newDaoPoolFactory(
      _daoName: PromiseOrValue<string>,
      _daoProfile: PromiseOrValue<string>,
      _daoIcon: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    newUserPoolFactory(
      _userName: PromiseOrValue<string>,
      _userProfile: PromiseOrValue<string>,
      _userIcon: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    usersData(overrides?: CallOverrides): Promise<[string]>;
  };

  daosData(overrides?: CallOverrides): Promise<string>;

  getMyPoolAddress(
    _ownerAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  newDaoPoolFactory(
    _daoName: PromiseOrValue<string>,
    _daoProfile: PromiseOrValue<string>,
    _daoIcon: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  newUserPoolFactory(
    _userName: PromiseOrValue<string>,
    _userProfile: PromiseOrValue<string>,
    _userIcon: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  usersData(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    daosData(overrides?: CallOverrides): Promise<string>;

    getMyPoolAddress(
      _ownerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    newDaoPoolFactory(
      _daoName: PromiseOrValue<string>,
      _daoProfile: PromiseOrValue<string>,
      _daoIcon: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    newUserPoolFactory(
      _userName: PromiseOrValue<string>,
      _userProfile: PromiseOrValue<string>,
      _userIcon: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    usersData(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    daosData(overrides?: CallOverrides): Promise<BigNumber>;

    getMyPoolAddress(
      _ownerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    newDaoPoolFactory(
      _daoName: PromiseOrValue<string>,
      _daoProfile: PromiseOrValue<string>,
      _daoIcon: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    newUserPoolFactory(
      _userName: PromiseOrValue<string>,
      _userProfile: PromiseOrValue<string>,
      _userIcon: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    usersData(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    daosData(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMyPoolAddress(
      _ownerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    newDaoPoolFactory(
      _daoName: PromiseOrValue<string>,
      _daoProfile: PromiseOrValue<string>,
      _daoIcon: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    newUserPoolFactory(
      _userName: PromiseOrValue<string>,
      _userProfile: PromiseOrValue<string>,
      _userIcon: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    usersData(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
