/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type { FunctionFragment, Result } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from './common';

export declare namespace SharedStruct {
  export type DaoStruct = {
    daoAddres: PromiseOrValue<string>;
    daoName: PromiseOrValue<string>;
    daoProfile: PromiseOrValue<string>;
    daoIcon: PromiseOrValue<string>;
  };

  export type DaoStructOutput = [string, string, string, string] & {
    daoAddres: string;
    daoName: string;
    daoProfile: string;
    daoIcon: string;
  };

  export type UserStruct = {
    userAddress: PromiseOrValue<string>;
    userName: PromiseOrValue<string>;
    userProfile: PromiseOrValue<string>;
    userIcon: PromiseOrValue<string>;
  };

  export type UserStructOutput = [string, string, string, string] & {
    userAddress: string;
    userName: string;
    userProfile: string;
    userIcon: string;
  };

  export type ProjectStruct = {
    belongDaoAddress: PromiseOrValue<string>;
    projectName: PromiseOrValue<string>;
    projectContents: PromiseOrValue<string>;
    projectReword: PromiseOrValue<string>;
  };

  export type ProjectStructOutput = [string, string, string, string] & {
    belongDaoAddress: string;
    projectName: string;
    projectContents: string;
    projectReword: string;
  };
}

export interface CheersInterface extends utils.Interface {
  functions: {
    'addProjects(address,address,string,string,string)': FunctionFragment;
    'eachProjectsList(address,uint256)': FunctionFragment;
    'getAllDaoList()': FunctionFragment;
    'getAllUserList()': FunctionFragment;
    'getEachProjectList(address)': FunctionFragment;
    'getMyPoolAddress(address)': FunctionFragment;
    'newDaoPoolFactory(string,string,string)': FunctionFragment;
    'newUserPoolFactory(string,string,string)': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | 'addProjects'
      | 'eachProjectsList'
      | 'getAllDaoList'
      | 'getAllUserList'
      | 'getEachProjectList'
      | 'getMyPoolAddress'
      | 'newDaoPoolFactory'
      | 'newUserPoolFactory',
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: 'addProjects',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
    ],
  ): string;
  encodeFunctionData(
    functionFragment: 'eachProjectsList',
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>],
  ): string;
  encodeFunctionData(functionFragment: 'getAllDaoList', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getAllUserList', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getEachProjectList', values: [PromiseOrValue<string>]): string;
  encodeFunctionData(functionFragment: 'getMyPoolAddress', values: [PromiseOrValue<string>]): string;
  encodeFunctionData(
    functionFragment: 'newDaoPoolFactory',
    values: [PromiseOrValue<string>, PromiseOrValue<string>, PromiseOrValue<string>],
  ): string;
  encodeFunctionData(
    functionFragment: 'newUserPoolFactory',
    values: [PromiseOrValue<string>, PromiseOrValue<string>, PromiseOrValue<string>],
  ): string;

  decodeFunctionResult(functionFragment: 'addProjects', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'eachProjectsList', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getAllDaoList', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getAllUserList', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getEachProjectList', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getMyPoolAddress', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'newDaoPoolFactory', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'newUserPoolFactory', data: BytesLike): Result;

  events: {};
}

export interface Cheers extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CheersInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addProjects(
      _projectOwnerAddress: PromiseOrValue<string>,
      _belongDaoAddress: PromiseOrValue<string>,
      _projectName: PromiseOrValue<string>,
      _projectContents: PromiseOrValue<string>,
      _projectReword: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    eachProjectsList(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<
      [string, string, string, string] & {
        belongDaoAddress: string;
        projectName: string;
        projectContents: string;
        projectReword: string;
      }
    >;

    getAllDaoList(overrides?: CallOverrides): Promise<[SharedStruct.DaoStructOutput[]]>;

    getAllUserList(overrides?: CallOverrides): Promise<[SharedStruct.UserStructOutput[]]>;

    getEachProjectList(
      _projectOwnerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<[SharedStruct.ProjectStructOutput[]]>;

    getMyPoolAddress(_ownerAddress: PromiseOrValue<string>, overrides?: CallOverrides): Promise<[string]>;

    newDaoPoolFactory(
      _daoName: PromiseOrValue<string>,
      _daoProfile: PromiseOrValue<string>,
      _daoIcon: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;

    newUserPoolFactory(
      _userName: PromiseOrValue<string>,
      _userProfile: PromiseOrValue<string>,
      _userIcon: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<ContractTransaction>;
  };

  addProjects(
    _projectOwnerAddress: PromiseOrValue<string>,
    _belongDaoAddress: PromiseOrValue<string>,
    _projectName: PromiseOrValue<string>,
    _projectContents: PromiseOrValue<string>,
    _projectReword: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  eachProjectsList(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides,
  ): Promise<
    [string, string, string, string] & {
      belongDaoAddress: string;
      projectName: string;
      projectContents: string;
      projectReword: string;
    }
  >;

  getAllDaoList(overrides?: CallOverrides): Promise<SharedStruct.DaoStructOutput[]>;

  getAllUserList(overrides?: CallOverrides): Promise<SharedStruct.UserStructOutput[]>;

  getEachProjectList(
    _projectOwnerAddress: PromiseOrValue<string>,
    overrides?: CallOverrides,
  ): Promise<SharedStruct.ProjectStructOutput[]>;

  getMyPoolAddress(_ownerAddress: PromiseOrValue<string>, overrides?: CallOverrides): Promise<string>;

  newDaoPoolFactory(
    _daoName: PromiseOrValue<string>,
    _daoProfile: PromiseOrValue<string>,
    _daoIcon: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  newUserPoolFactory(
    _userName: PromiseOrValue<string>,
    _userProfile: PromiseOrValue<string>,
    _userIcon: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> },
  ): Promise<ContractTransaction>;

  callStatic: {
    addProjects(
      _projectOwnerAddress: PromiseOrValue<string>,
      _belongDaoAddress: PromiseOrValue<string>,
      _projectName: PromiseOrValue<string>,
      _projectContents: PromiseOrValue<string>,
      _projectReword: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<void>;

    eachProjectsList(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<
      [string, string, string, string] & {
        belongDaoAddress: string;
        projectName: string;
        projectContents: string;
        projectReword: string;
      }
    >;

    getAllDaoList(overrides?: CallOverrides): Promise<SharedStruct.DaoStructOutput[]>;

    getAllUserList(overrides?: CallOverrides): Promise<SharedStruct.UserStructOutput[]>;

    getEachProjectList(
      _projectOwnerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<SharedStruct.ProjectStructOutput[]>;

    getMyPoolAddress(_ownerAddress: PromiseOrValue<string>, overrides?: CallOverrides): Promise<string>;

    newDaoPoolFactory(
      _daoName: PromiseOrValue<string>,
      _daoProfile: PromiseOrValue<string>,
      _daoIcon: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<string>;

    newUserPoolFactory(
      _userName: PromiseOrValue<string>,
      _userProfile: PromiseOrValue<string>,
      _userIcon: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    addProjects(
      _projectOwnerAddress: PromiseOrValue<string>,
      _belongDaoAddress: PromiseOrValue<string>,
      _projectName: PromiseOrValue<string>,
      _projectContents: PromiseOrValue<string>,
      _projectReword: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    eachProjectsList(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    getAllDaoList(overrides?: CallOverrides): Promise<BigNumber>;

    getAllUserList(overrides?: CallOverrides): Promise<BigNumber>;

    getEachProjectList(_projectOwnerAddress: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

    getMyPoolAddress(_ownerAddress: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>;

    newDaoPoolFactory(
      _daoName: PromiseOrValue<string>,
      _daoProfile: PromiseOrValue<string>,
      _daoIcon: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;

    newUserPoolFactory(
      _userName: PromiseOrValue<string>,
      _userProfile: PromiseOrValue<string>,
      _userIcon: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addProjects(
      _projectOwnerAddress: PromiseOrValue<string>,
      _belongDaoAddress: PromiseOrValue<string>,
      _projectName: PromiseOrValue<string>,
      _projectContents: PromiseOrValue<string>,
      _projectReword: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    eachProjectsList(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    getAllDaoList(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAllUserList(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getEachProjectList(
      _projectOwnerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    getMyPoolAddress(_ownerAddress: PromiseOrValue<string>, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    newDaoPoolFactory(
      _daoName: PromiseOrValue<string>,
      _daoProfile: PromiseOrValue<string>,
      _daoIcon: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;

    newUserPoolFactory(
      _userName: PromiseOrValue<string>,
      _userProfile: PromiseOrValue<string>,
      _userIcon: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> },
    ): Promise<PopulatedTransaction>;
  };
}
