/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { ICheers, ICheersInterface } from "../../interfaces/ICheers";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_ownerAddress",
        type: "address",
      },
    ],
    name: "getMyPoolAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ICheers__factory {
  static readonly abi = _abi;
  static createInterface(): ICheersInterface {
    return new utils.Interface(_abi) as ICheersInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICheers {
    return new Contract(address, _abi, signerOrProvider) as ICheers;
  }
}
