/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as usersDataSol from "./UsersData.sol";
export type { usersDataSol };
export type { DaosData } from "./DaosData";
export type { ProjectsData } from "./ProjectsData";
