/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface DaoPoolFactoryInterface extends utils.Interface {
  functions: {
    "daosData()": FunctionFragment;
    "newDaoPoolFactory(string,string,string)": FunctionFragment;
    "poolListData()": FunctionFragment;
    "setDaosData(address)": FunctionFragment;
    "setPoolListData(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "daosData"
      | "newDaoPoolFactory"
      | "poolListData"
      | "setDaosData"
      | "setPoolListData"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "daosData", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "newDaoPoolFactory",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "poolListData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDaosData",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPoolListData",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "daosData", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "newDaoPoolFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolListData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDaosData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPoolListData",
    data: BytesLike
  ): Result;

  events: {};
}

export interface DaoPoolFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DaoPoolFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    daosData(overrides?: CallOverrides): Promise<[string]>;

    newDaoPoolFactory(
      _daoName: PromiseOrValue<string>,
      _daoProfile: PromiseOrValue<string>,
      _daoIcon: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    poolListData(overrides?: CallOverrides): Promise<[string]>;

    setDaosData(
      daosDataAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPoolListData(
      poolListDataAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  daosData(overrides?: CallOverrides): Promise<string>;

  newDaoPoolFactory(
    _daoName: PromiseOrValue<string>,
    _daoProfile: PromiseOrValue<string>,
    _daoIcon: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  poolListData(overrides?: CallOverrides): Promise<string>;

  setDaosData(
    daosDataAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPoolListData(
    poolListDataAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    daosData(overrides?: CallOverrides): Promise<string>;

    newDaoPoolFactory(
      _daoName: PromiseOrValue<string>,
      _daoProfile: PromiseOrValue<string>,
      _daoIcon: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    poolListData(overrides?: CallOverrides): Promise<string>;

    setDaosData(
      daosDataAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setPoolListData(
      poolListDataAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    daosData(overrides?: CallOverrides): Promise<BigNumber>;

    newDaoPoolFactory(
      _daoName: PromiseOrValue<string>,
      _daoProfile: PromiseOrValue<string>,
      _daoIcon: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    poolListData(overrides?: CallOverrides): Promise<BigNumber>;

    setDaosData(
      daosDataAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPoolListData(
      poolListDataAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    daosData(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    newDaoPoolFactory(
      _daoName: PromiseOrValue<string>,
      _daoProfile: PromiseOrValue<string>,
      _daoIcon: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    poolListData(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setDaosData(
      daosDataAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPoolListData(
      poolListDataAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
